version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/data
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./data/sql_app.db

volumes:
  sqlite_data: